@extends('layouts.app')

@section('content')
<div class="mb-5"><p class="text-sm font-semibold text-[#D71920]">Daily bank updates</p><h1 class="text-2xl font-bold text-gray-950">Bank Reconciliation</h1></div>
@if (auth()->user()->canManageCcc())
<div class="mb-5 grid gap-4 lg:grid-cols-2">
    <form method="POST" action="{{ route('ccc.bank-accounts.store') }}" class="pm-card grid gap-3 p-4 sm:grid-cols-2">@csrf<h2 class="font-bold text-gray-950 sm:col-span-2">Bank Account</h2><div><label class="pm-label">Bank</label><input class="pm-input" name="bank_name" required></div><div><label class="pm-label">Account Name</label><input class="pm-input" name="account_name" required></div><div><label class="pm-label">Account No.</label><input class="pm-input" name="account_number"></div><div><label class="pm-label">Opening Balance</label><input class="pm-input" type="number" step="0.01" name="opening_balance" value="0"></div><div class="sm:col-span-2"><button class="pm-btn-secondary">Add Account</button></div></form>
    <form method="POST" action="{{ route('ccc.bank-imports.store') }}" enctype="multipart/form-data" class="pm-card grid gap-3 p-4 sm:grid-cols-2">@csrf<h2 class="font-bold text-gray-950 sm:col-span-2">Upload CSV</h2><div><label class="pm-label">Account</label><select class="pm-input" name="bank_account_id" required>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->bank_name }} · {{ $account->account_name }}</option>@endforeach</select></div><div><label class="pm-label">Statement Date</label><input class="pm-input" type="date" name="statement_date" value="{{ now()->format('Y-m-d') }}" required></div><div><label class="pm-label">Provider</label><select class="pm-input" name="bank_provider"><option>Maybank</option><option>CIMB</option><option>RHB</option><option>Hong Leong</option><option>Public Bank</option></select></div><div><label class="pm-label">CSV File</label><input class="pm-input" type="file" name="csv_file" required></div><div class="sm:col-span-2"><button class="pm-btn-primary">Import CSV</button></div></form>
</div>
@endif
<div class="grid gap-4 lg:grid-cols-3"><section class="pm-card p-4"><h2 class="font-bold text-gray-950">Recent Imports</h2><div class="mt-3 space-y-3">@forelse($imports as $import)<div class="text-sm"><p class="font-semibold">{{ $import->account?->bank_name }} · {{ $import->statement_date->format('d M Y') }}</p><p class="text-gray-500">{{ $import->rows_imported }} imported · {{ $import->duplicates_skipped }} duplicates</p></div>@empty<p class="text-sm text-gray-500">No imports yet.</p>@endforelse</div></section><section class="pm-card overflow-hidden lg:col-span-2"><table class="w-full text-left text-sm"><thead class="bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="px-4 py-3">Date</th><th>Description</th><th>Debit</th><th>Credit</th><th>Status</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($transactions as $txn)<tr><td class="px-4 py-3">{{ $txn->transaction_date->format('d M Y') }}</td><td>{{ $txn->description }}</td><td>RM {{ number_format((float) $txn->debit, 2) }}</td><td>RM {{ number_format((float) $txn->credit, 2) }}</td><td>{{ str($txn->match_status)->headline() }}</td></tr>@empty<tr><td colspan="5" class="px-4 py-6 text-center text-gray-500">No bank transactions imported.</td></tr>@endforelse</tbody></table><div class="p-4">{{ $transactions->links() }}</div></section></div>
@endsection
