@extends('layouts.app')

@section('content')
<div class="mb-5"><p class="text-sm font-semibold text-[#D71920]">Supplier relationship history</p><h1 class="text-2xl font-bold text-gray-950">Communication Logs</h1></div>
@if (auth()->user()->canManageCcc())
<form method="POST" action="{{ route('ccc.communication-logs.store') }}" class="pm-card mb-5 grid gap-3 p-4 md:grid-cols-4">@csrf<div><label class="pm-label">Creditor</label><select class="pm-input" name="creditor_id">@foreach($creditors as $creditor)<option value="{{ $creditor->id }}">{{ $creditor->creditor_name }}</option>@endforeach</select></div><div><label class="pm-label">Date</label><input class="pm-input" type="date" name="date" value="{{ now()->format('Y-m-d') }}"></div><div><label class="pm-label">Type</label><select class="pm-input" name="type"><option value="call">Call</option><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="meeting">Meeting</option></select></div><div><label class="pm-label">Promise Amount</label><input class="pm-input" type="number" step="0.01" name="promise_amount"></div><div><label class="pm-label">Promise Date</label><input class="pm-input" type="date" name="promise_date"></div><div><label class="pm-label">Next Follow Up</label><input class="pm-input" type="date" name="next_follow_up_date"></div><div class="md:col-span-2"><label class="pm-label">Outcome</label><input class="pm-input" name="outcome"></div><div class="md:col-span-4"><button class="pm-btn-primary">Save Log</button></div></form>
@endif
<section class="pm-card overflow-hidden"><table class="w-full text-left text-sm"><thead class="bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="px-4 py-3">Date</th><th>Creditor</th><th>Type</th><th>Outcome</th><th>Promise</th><th>Next Follow Up</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($items as $item)<tr><td class="px-4 py-3">{{ $item->date->format('d M Y') }}</td><td class="font-semibold">{{ $item->creditor->creditor_name }}</td><td>{{ str($item->type)->headline() }}</td><td>{{ $item->outcome }}</td><td>{{ $item->promise_amount ? 'RM '.number_format((float) $item->promise_amount, 2) : '' }} {{ $item->promise_date?->format('d M') }}</td><td>{{ $item->next_follow_up_date?->format('d M Y') }}</td></tr>@empty<tr><td colspan="6" class="px-4 py-6 text-center text-gray-500">No communication logs yet.</td></tr>@endforelse</tbody></table><div class="p-4">{{ $items->links() }}</div></section>
@endsection
