@extends('layouts.app')

@section('content')
<div class="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-[#D71920]">Master data</p><h1 class="text-2xl font-bold text-gray-950">Creditors</h1></div><div class="flex gap-2"><a class="pm-btn-secondary" href="{{ route('ccc.debts') }}">Debt Records</a><a class="pm-btn-secondary" href="{{ route('ccc.communication-logs') }}">Communication Logs</a></div></div>
@if (auth()->user()->canManageCcc())
<form method="POST" action="{{ route('ccc.creditors.store') }}" class="pm-card mb-5 grid gap-3 p-4 md:grid-cols-4">@csrf
    <div><label class="pm-label">Creditor Name</label><input class="pm-input" name="creditor_name" required></div><div><label class="pm-label">Company</label><input class="pm-input" name="company_name"></div><div><label class="pm-label">Contact</label><input class="pm-input" name="contact_person"></div><div><label class="pm-label">Phone</label><input class="pm-input" name="phone"></div>
    <div><label class="pm-label">Email</label><input class="pm-input" type="email" name="email"></div><div><label class="pm-label">Bank</label><input class="pm-input" name="bank_name"></div><div><label class="pm-label">Account No.</label><input class="pm-input" name="bank_account_number"></div><div><label class="pm-label">Opening Balance</label><input class="pm-input" type="number" step="0.01" name="opening_balance" value="0" required></div>
    <div><label class="pm-label">Priority</label><select class="pm-input" name="priority"><option value="critical">Critical</option><option value="high">High</option><option value="normal" selected>Normal</option><option value="low">Low</option></select></div><div><label class="pm-label">Risk</label><input class="pm-input" type="number" min="1" max="5" name="relationship_risk" value="3"></div><div><label class="pm-label">Status</label><select class="pm-input" name="status"><option value="active">Active</option><option value="fully_paid">Fully Paid</option><option value="kiv">KIV</option><option value="disputed">Disputed</option></select></div><div class="flex items-end"><button class="pm-btn-primary w-full">Create</button></div>
    <div class="md:col-span-4"><label class="pm-label">Notes</label><textarea class="pm-input" name="notes" rows="2"></textarea></div>
</form>
@endif
<section class="pm-card overflow-hidden"><table class="w-full text-left text-sm"><thead class="bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="px-4 py-3">Creditor</th><th>Contact</th><th>Priority</th><th>Status</th><th>Debts</th><th class="text-right">Outstanding</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($items as $item)<tr><td class="px-4 py-3"><div class="font-semibold">{{ $item->creditor_name }}</div><div class="text-xs text-gray-500">{{ $item->company_name }}</div></td><td>{{ $item->contact_person }}<div class="text-xs text-gray-500">{{ $item->phone }}</div></td><td>{{ str($item->priority)->headline() }}</td><td>{{ str($item->status)->headline() }}</td><td>{{ $item->debts_count }}</td><td class="px-4 py-3 text-right font-bold">RM {{ number_format((float) $item->current_outstanding, 2) }}</td></tr>@empty<tr><td colspan="6" class="px-4 py-6 text-center text-gray-500">No creditors yet.</td></tr>@endforelse</tbody></table><div class="p-4">{{ $items->links() }}</div></section>
@endsection
