@extends('layouts.app')

@section('content')
<div class="mb-5"><p class="text-sm font-semibold text-[#D71920]">Financial and automation controls</p><h1 class="text-2xl font-bold text-gray-950">CCC Settings</h1></div>
@php($finance = $financial->value ?? [])
@php($mail = $smtp->value ?? [])
<form method="POST" action="{{ route('ccc.settings.update') }}" class="grid gap-4 lg:grid-cols-2">@csrf @method('PUT')
    <section class="pm-card grid gap-3 p-4 sm:grid-cols-2"><h2 class="font-bold text-gray-950 sm:col-span-2">Financial Settings</h2><div><label class="pm-label">Minimum Reserve</label><input class="pm-input" type="number" step="0.01" name="minimum_cash_reserve" value="{{ $finance['minimum_cash_reserve'] ?? 0 }}"></div><div><label class="pm-label">Weekly Debt Budget</label><input class="pm-input" type="number" step="0.01" name="weekly_debt_budget" value="{{ $finance['weekly_debt_budget'] ?? 0 }}"></div><div><label class="pm-label">Monthly Debt Target</label><input class="pm-input" type="number" step="0.01" name="monthly_debt_target" value="{{ $finance['monthly_debt_target'] ?? 0 }}"></div><div><label class="pm-label">Overdue Threshold</label><input class="pm-input" type="number" name="overdue_threshold" value="{{ $finance['overdue_threshold'] ?? 30 }}"></div><div><label class="pm-label">Critical Threshold</label><input class="pm-input" type="number" step="0.01" name="critical_creditor_threshold" value="{{ $finance['critical_creditor_threshold'] ?? 0 }}"></div></section>
    <section class="pm-card grid gap-3 p-4 sm:grid-cols-2"><h2 class="font-bold text-gray-950 sm:col-span-2">SMTP Settings</h2><div><label class="pm-label">Host</label><input class="pm-input" name="smtp_host" value="{{ $mail['smtp_host'] ?? '' }}"></div><div><label class="pm-label">Port</label><input class="pm-input" type="number" name="smtp_port" value="{{ $mail['smtp_port'] ?? 587 }}"></div><div><label class="pm-label">Username</label><input class="pm-input" name="smtp_username" value="{{ $mail['smtp_username'] ?? '' }}"></div><div><label class="pm-label">Password</label><input class="pm-input" name="smtp_password" type="password" value="{{ $mail['smtp_password'] ?? '' }}"></div><div><label class="pm-label">Encryption</label><input class="pm-input" name="smtp_encryption" value="{{ $mail['smtp_encryption'] ?? 'tls' }}"></div><div><label class="pm-label">Sender Email</label><input class="pm-input" type="email" name="sender_email" value="{{ $mail['sender_email'] ?? 'hq@physiomobile.com' }}"></div><div class="sm:col-span-2"><label class="pm-label">Sender Name</label><input class="pm-input" name="sender_name" value="{{ $mail['sender_name'] ?? 'PMMY Group' }}"></div></section>
    @if(auth()->user()->isDirector())<div class="lg:col-span-2"><button class="pm-btn-primary">Save Settings</button></div>@endif
</form>
@endsection
